version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn add -D jest-junit

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: 
          name: Run test suites with reporters
          command: yarn test:circleci
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

      - store_test_results:
          path: "reports"

      - store_artifacts:
          path: "reports/junit/js-test-results.xml"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
